### PR TITLE
[WIP] Feature/hero display

### PR DESCRIPTION
**Pull request by LoyVanBeek**
<strike>The output via `journalctl` is:
```
Jun 11 20:40:07 hero1 systemd[1]: Started Head display on Hero's head.
Jun 11 20:40:08 hero1 systemd[1]: hero1-display.service: Main process exited, code=exited, status=1/FAILURE
Jun 11 20:40:08 hero1 systemd[1]: hero1-display.service: Unit entered failed state.
Jun 11 20:40:08 hero1 systemd[1]: hero1-display.service: Failed with result 'exit-code'.
```
While running the same executeable manually is fine and shows the UI. 

I have no clue what is wrong right now. </strike>

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Doesn't work, probably needs to wait till xserver. This might be helpful: https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg

**Comment by LoyVanBeek** [comment]
Auto-start is almost working, however gnome-desktop is displayed on top. 
Leaves a few options:
- Start after gnome-desktop/lightdm etc. 
- Start not via systemd by via gnome startup applications. But then we can't start/stop etc and loose journalctl output
- Specify 'always-on-top' on commandline

**Comment by LoyVanBeek** [comment]
Not needed anymore, autostart is now done by Gnome

**Comment by MatthijsBurgh** [comment]
I will open an issue, for adding the autostart to the documentation.

**Pull request closed without merging**
