### PR TITLE
fix gazebo control param ns

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
I don't know when this started. I also didn't experience any problems yet, but it produced errors, red print. So that should be solved right now.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@PetervDooren @LarsJanssenTUe could you test this on your PCs? Without this I get a lot of red when running `hero-start`. With this fix, it is gone.

**Comment by PetervDooren** [comment]
No problems for me

**Comment by LarsJanssenTUe** [comment]
> No problems for me

Samesies!

**Comment by MatthijsBurgh** [comment]
I don't know it if is related to the new TMC update, but I definitely need it with the 20.04 update. So something similar is included in #57

**Pull request merged**
