### PR TITLE
(localization) Use 2x more laser beams

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Review by PetervDooren — CHANGES_REQUESTED** [review]
This will not help imo. 
This was a hotfix you made last night, it was not properly tested. 
If we want to solve this problem (if there is any at all) we need to properly think about it.

**Comment by MatthijsBurgh** [comment]
This is not a fix for localization during manipulation etc.

This is a fix for global localization. HERO does lose its global localization from time to time while just driving around. Its pose can be of for more than 1m and/or its rotation can be for minimal 20 degrees. That shouldn't happen.

**Comment by MatthijsBurgh** [comment]
Test it yourself. Just drive around in impuls for 15 minutes without and 15 with this change.

**Review by PetervDooren — CHANGES_REQUESTED** [review]
You claim this but I don't think you sufficiently tested the original behaviour and then compared it to this behaviour. The error in localization could also be a fault in other parameters. It is too quick to make this change

**Comment by MatthijsBurgh** [comment]
The number of beams can also include NaNs or max range, which are excluded.

**Comment by MatthijsBurgh** [comment]
Superseded by https://github.com/tue-robotics/hero_bringup/pull/128

**Pull request closed without merging**
