### PR TITLE
Start the hand camera

### PR DESCRIPTION
**Pull request by PetervDooren**
One of our BEP students will be using the handcamera next semester. And its useful in general.

### CODE REVIEW

**Comment by PetervDooren** [comment]
CI errors unrelated to these changes. Toyota packages could not be found.

**Comment by MatthijsBurgh** [comment]
Useful, but also requires resources. So when needed, we run it. But when stuff doesn't get integrated, we should revert it in the future.

**Comment by MatthijsBurgh** [comment]
I will take a look at the CI, before merging this.

**Comment by MatthijsBurgh** [comment]
Merging this as the CI issue is a difficult one.

**Pull request merged**
